In [8]:
import numpy as np
import os
import pandas as pd
from collections import Counter
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import nltk

In [9]:
#to list all the folders in the main folder
direc="F:\\Machine Learning CN\\20_newsgroups\\"
files=os.listdir(direc)

In [10]:
news=[direc+new for new in files] #to save the directery of every folder
news

['F:\\Machine Learning CN\\20_newsgroups\\alt.atheism',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.graphics',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.os.ms-windows.misc',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.sys.ibm.pc.hardware',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.sys.mac.hardware',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.windows.x',
 'F:\\Machine Learning CN\\20_newsgroups\\misc.forsale',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.autos',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.motorcycles',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.sport.baseball',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.sport.hockey',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.crypt',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.electronics',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.med',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.space',
 'F:\\Machine Learning CN\\20_newsgroups\\soc.religion.christian',
 'F:\\Machine Learning CN\\20_newsgroups\\

In [11]:
#empty lists
directeries=[] #to save the path of each file in the subfolders
all_words=[]   #to save all the words in all the files

In [12]:
#a list of some stopwords that are to eliminated
stop_words=["a",
"about"
"above"
"after"
"again"
"against"
"all"
"am",
"an",
"and",
"any",
"are",
"aren't",
'as',
'at',
'be',
'because',
'been',
'before',
'being',
'below',
'between',
'both',
'but',
'by','can','will','about','all','may','apr'
"can't",
'cannot',
'could',
"couldn't",
'did',
"didn't",
'do',
'does',
"doesn't",
'doing',
"don't",
'down',
'during',
'each',
'few',
'for',
'from',
'further',
'had',
"hadn't",
'has',
"hasn't",
'have',
"haven't",
'having',
'he',
"he'd",
"he'll",
"he's",
'her',
'here',
"here's",
'hers',
'herself',
'him',
'himself',
'his',
'how',
"how's",
'i',
"i'd",
"i'll",
"i'm",
"i've",
'if',
'in',
'into',
'is',
"isn't",
'it',
"it's",
'its',
'itself',
"let's",
'me',
'more',
'most',
"mustn't",
'my',
'myself',
'no',
'nor',
'not',
'of',
'off',
'on',
'once',
'only',
'or',
'other',
'ought',
'our',
'ours',
'ourselves',
'out',
'over',
'own',
'same',
"shan't",
'she',
"she'd",
"she'll",
"she's",
'should',
"shouldn't",
'so',
'some',
'such',
'than',
'that',
"that's",
'the',
'their',
'theirs',
'them',
'themselves',
'then',
'there',
"there's",
'these',
'they',
"they'd",
"they'll",
"they're",
"they've",
'this',
'those',
'through',
'to',
'too',
'under',
'until',
'up',
'very',
'was',
"wasn't",
'we',
"we'd",
"we'll",
"we're",
"we've",
'were',
"weren't",
'what',
"what's",
'when',"can",'will','about','all'
"when's",
'where',
"where's",
'which','sender','one','path','xref'
'while',
'who',
"who's",
'whom',
'why',
"why's",
'with',
"won't",
'would',
"wouldn't",'newsgroups'
'you',
"you'd",
"you'll",
"you're",
"you've",
'your',
'yours',
'yourself',
'yourselves']

In [13]:
for new in news:
    #it saves the path of each file in the subfolder
    f=os.listdir(new)
    new_list=[]
    for a in f:
        new_list.append(new+"\\"+a)
    directeries.append(new_list)
    
    
for new in directeries:
    for alls in new:
        #it opens each file,read it and split it into different words and add it to the list all_words
        f=open(alls,"r")
        cdf=f.read()
        #new_word=cdf.split(" ")
        all_words+=nltk.word_tokenize(cdf)

In [7]:
all_words

['Xref',
 ':',
 'cantaloupe.srv.cs.cmu.edu',
 'alt.atheism:49960',
 'alt.atheism.moderated:713',
 'news.answers:7054',
 'alt.answers:126',
 'Path',
 ':',
 'cantaloupe.srv.cs.cmu.edu',
 '!',
 'crabapple.srv.cs.cmu.edu',
 '!',
 'bb3.andrew.cmu.edu',
 '!',
 'news.sei.cmu.edu',
 '!',
 'cis.ohio-state.edu',
 '!',
 'magnus.acs.ohio-state.edu',
 '!',
 'usenet.ins.cwru.edu',
 '!',
 'agate',
 '!',
 'spool.mu.edu',
 '!',
 'uunet',
 '!',
 'pipex',
 '!',
 'ibmpcug',
 '!',
 'mantis',
 '!',
 'mathew',
 'From',
 ':',
 'mathew',
 '<',
 'mathew',
 '@',
 'mantis.co.uk',
 '>',
 'Newsgroups',
 ':',
 'alt.atheism',
 ',',
 'alt.atheism.moderated',
 ',',
 'news.answers',
 ',',
 'alt.answers',
 'Subject',
 ':',
 'Alt.Atheism',
 'FAQ',
 ':',
 'Atheist',
 'Resources',
 'Summary',
 ':',
 'Books',
 ',',
 'addresses',
 ',',
 'music',
 '--',
 'anything',
 'related',
 'to',
 'atheism',
 'Keywords',
 ':',
 'FAQ',
 ',',
 'atheism',
 ',',
 'books',
 ',',
 'music',
 ',',
 'fiction',
 ',',
 'addresses',
 ',',
 'contacts'

In [14]:
for i in range(len(all_words)):
    #to convert each word into lower case character as it becomes easy to process them
    all_words[i]=all_words[i].lower()

In [9]:
all_words

['xref',
 ':',
 'cantaloupe.srv.cs.cmu.edu',
 'alt.atheism:49960',
 'alt.atheism.moderated:713',
 'news.answers:7054',
 'alt.answers:126',
 'path',
 ':',
 'cantaloupe.srv.cs.cmu.edu',
 '!',
 'crabapple.srv.cs.cmu.edu',
 '!',
 'bb3.andrew.cmu.edu',
 '!',
 'news.sei.cmu.edu',
 '!',
 'cis.ohio-state.edu',
 '!',
 'magnus.acs.ohio-state.edu',
 '!',
 'usenet.ins.cwru.edu',
 '!',
 'agate',
 '!',
 'spool.mu.edu',
 '!',
 'uunet',
 '!',
 'pipex',
 '!',
 'ibmpcug',
 '!',
 'mantis',
 '!',
 'mathew',
 'from',
 ':',
 'mathew',
 '<',
 'mathew',
 '@',
 'mantis.co.uk',
 '>',
 'newsgroups',
 ':',
 'alt.atheism',
 ',',
 'alt.atheism.moderated',
 ',',
 'news.answers',
 ',',
 'alt.answers',
 'subject',
 ':',
 'alt.atheism',
 'faq',
 ':',
 'atheist',
 'resources',
 'summary',
 ':',
 'books',
 ',',
 'addresses',
 ',',
 'music',
 '--',
 'anything',
 'related',
 'to',
 'atheism',
 'keywords',
 ':',
 'faq',
 ',',
 'atheism',
 ',',
 'books',
 ',',
 'music',
 ',',
 'fiction',
 ',',
 'addresses',
 ',',
 'contacts'

In [15]:
for i in range(len(all_words)):
    #to remove all the non alphabetic words in the list
    if all_words[i].isalpha():
        continue
    else:
        all_words[i]='' #changing each non alphabetic word to an empty string and delete it later

In [11]:
all_words

['xref',
 '',
 '',
 '',
 '',
 '',
 '',
 'path',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'agate',
 '',
 '',
 '',
 'uunet',
 '',
 'pipex',
 '',
 'ibmpcug',
 '',
 'mantis',
 '',
 'mathew',
 'from',
 '',
 'mathew',
 '',
 'mathew',
 '',
 '',
 '',
 'newsgroups',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'subject',
 '',
 '',
 'faq',
 '',
 'atheist',
 'resources',
 'summary',
 '',
 'books',
 '',
 'addresses',
 '',
 'music',
 '',
 'anything',
 'related',
 'to',
 'atheism',
 'keywords',
 '',
 'faq',
 '',
 'atheism',
 '',
 'books',
 '',
 'music',
 '',
 'fiction',
 '',
 'addresses',
 '',
 'contacts',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'date',
 '',
 'mon',
 '',
 '',
 'mar',
 '',
 '',
 'gmt',
 'expires',
 '',
 'thu',
 '',
 '',
 'apr',
 '',
 '',
 'gmt',
 '',
 '',
 '',
 'distribution',
 '',
 'world',
 'organization',
 '',
 'mantis',
 'consultants',
 '',
 'cambridge',
 '',
 'uk',
 '',
 'approved',
 '',
 '',
 '',
 '',
 'supersedes',
 '',
 '',
 '',
 '',
 '',
 '',
 'lin

In [16]:
for i in range(len(all_words)):
    #to remove all the stop words in the list of all words
    if not all_words[i] in stop_words:
        continue
    else:
        all_words[i]=''  #in this also,changing all stop words to empty string

In [13]:
all_words

['xref',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'agate',
 '',
 '',
 '',
 'uunet',
 '',
 'pipex',
 '',
 'ibmpcug',
 '',
 'mantis',
 '',
 'mathew',
 '',
 '',
 'mathew',
 '',
 'mathew',
 '',
 '',
 '',
 'newsgroups',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'subject',
 '',
 '',
 'faq',
 '',
 'atheist',
 'resources',
 'summary',
 '',
 'books',
 '',
 'addresses',
 '',
 'music',
 '',
 'anything',
 'related',
 '',
 'atheism',
 'keywords',
 '',
 'faq',
 '',
 'atheism',
 '',
 'books',
 '',
 'music',
 '',
 'fiction',
 '',
 'addresses',
 '',
 'contacts',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'date',
 '',
 'mon',
 '',
 '',
 'mar',
 '',
 '',
 'gmt',
 'expires',
 '',
 'thu',
 '',
 '',
 'apr',
 '',
 '',
 'gmt',
 '',
 '',
 '',
 'distribution',
 '',
 'world',
 'organization',
 '',
 'mantis',
 'consultants',
 '',
 'cambridge',
 '',
 'uk',
 '',
 'approved',
 '',
 '',
 '',
 '',
 'supersedes',
 '',
 '',
 '',
 '',
 '',
 '',
 'lines',
 '',


In [17]:
#using an inbuilt function to count all the occurences of each word and save it to dictionary
dictionary=Counter(all_words)
del dictionary['']       #deleting the empty string
del dictionary['newsgroups']
del dictionary['news']
del dictionary['references']
del dictionary['date']
del dictionary['xref']
del dictionary['you']
del dictionary['m']
del dictionary['uunet']
del dictionary['think']
del dictionary['also']
del dictionary['use']
del dictionary['x']
print(dictionary.most_common(3000))
dictionary=dictionary.most_common(500)  #taking first 3000 common words

[('subject', 21568), ('lines', 20875), ('organization', 19765), ('apr', 19624), ('gmt', 17760), ('writes', 14679), ('re', 14506), ('article', 12600), ('people', 10299), ('like', 10161), ('just', 9929), ('university', 9911), ('know', 9077), ('get', 8646), ('time', 6685), ('new', 6549), ('good', 6203), ('system', 6033), ('now', 5741), ('even', 5708), ('am', 5648), ('well', 5643), ('see', 5512), ('usenet', 5503), ('god', 5227), ('way', 5210), ('say', 5180), ('make', 5157), ('many', 5102), ('much', 5075), ('first', 4988), ('us', 4976), ('two', 4963), ('right', 4820), ('distribution', 4748), ('max', 4720), ('world', 4632), ('after', 4484), ('want', 4419), ('anyone', 4347), ('said', 4308), ('ca', 4237), ('used', 4224), ('rochester', 4218), ('go', 4186), ('need', 4140), ('q', 4134), ('work', 3888), ('really', 3824), ('please', 3792), ('something', 3771), ('problem', 3749), ('christian', 3729), ('r', 3715), ('gatech', 3703), ('believe', 3687), ('since', 3670), ('computer', 3635), ('still', 355

In [18]:
#our dictionary is made with all words and its count


In [19]:
#now again making directery for each folder
news=[direc+new for new in files]
news

['F:\\Machine Learning CN\\20_newsgroups\\alt.atheism',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.graphics',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.os.ms-windows.misc',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.sys.ibm.pc.hardware',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.sys.mac.hardware',
 'F:\\Machine Learning CN\\20_newsgroups\\comp.windows.x',
 'F:\\Machine Learning CN\\20_newsgroups\\misc.forsale',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.autos',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.motorcycles',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.sport.baseball',
 'F:\\Machine Learning CN\\20_newsgroups\\rec.sport.hockey',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.crypt',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.electronics',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.med',
 'F:\\Machine Learning CN\\20_newsgroups\\sci.space',
 'F:\\Machine Learning CN\\20_newsgroups\\soc.religion.christian',
 'F:\\Machine Learning CN\\20_newsgroups\\

In [20]:
#empty lists
directeries=[] #to save the path of each file in the subfolders

In [21]:
#creating empty lists
feature_set=[]   #for feature set which will include the count of each word in that particular file
labels=[]        #to save labels of the files

In [22]:
for new in news:
    #same again , saving the path of each folder in the main folder in directeries list
    f=os.listdir(new)
    new_list=[]
    for a in f:
        new_list.append(new+"\\"+a)
    directeries.append(new_list)

In [23]:
for new in directeries:
    #to access each file in the folder
    for alls in new:
        #to access each word in the file
        data=[]   #temporary list to save words in each file
        f=open(alls,"r")
        sentences=nltk.word_tokenize(f.read())  #read each word and tokenizes it into different words
        for entry in dictionary:
            #to access each word in the dictionary
            data.append(sentences.count(entry[0]))  #using inbuild function to count the occerence of each word of dictionary 
                                                    #in a particular file and add it to data list
        feature_set.append(data)                    #adding each data list to feature set
        labels.append(alls[37:-6])                  #adding each label to labels list
#labels[0]

In [24]:
feature_set=np.array(feature_set)
print(feature_set)

[[0 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 2]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
labels=np.array(labels)
print(labels)

['alt.atheism' 'alt.atheism' 'alt.atheism' ... 'talk.religion.misc'
 'talk.religion.misc' 'talk.religion.misc']


In [26]:
len(labels),len(feature_set)  #should be equal

(19997, 19997)

In [27]:
#splitting the feature set into training and testing
x_train,x_test,y_train,y_test=train_test_split(feature_set,labels)

In [28]:
#using multinomial naive bayes from sklearn
clf=MultinomialNB()

In [29]:
#fiting the data
clf.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [30]:
#predicting the data and saving to predicted
predicted=clf.predict(x_test)

In [31]:
#printing the accuracy score on using sklearn
print(accuracy_score(y_test,predicted))

0.5134


In [32]:
#Implementing Naive Bayes on my own from scratch 

In [33]:
def fit(feature_set,labels):
    result={}   #initialising the dictionary to save all the counts
    labels_value=set(labels)     #getting ditinct label in the labels list
    #print(labels_value)
    for label in labels_value:
        current_row=[]
        #going through each distinct label
        result[label]={}            #to save each row with label as label 
        current_class_rows=(labels==label)        #this will give each row with label as label
        #print(current_class_rows)
        feature_current=feature_set[current_class_rows]   #create a feature set with only rows where label is label
        labels_current=labels[current_class_rows]     #create a output set with only the current label
        #print(feature_current)
        num_features=len(feature_set[0])
        result[label]["total"]=0      #total features with current label (initialised to 0)
        for j in range(0,num_features):
            #updating the sum when a word is found
            result[label][j]= feature_current[:,j].sum()
        for j in range(0,num_features):
            #add all the rows with current label
            result[label]["total"]+=result[label][j]
    return result

In [35]:
y_train

array(['comp.sys.ibm.pc.hardware', 'rec.motorcycles\\',
       'comp.sys.mac.hardware', ..., 'rec.sport.baseball\\',
       'comp.sys.ibm.pc.hardware', 'sci.electronics'], dtype='<U24')

In [36]:
def probability(count,x,current_class):
    #to find the probability that a given document is of given class
    num_features=len(count[current_class].keys())-1   #total count
    prob=0.0        #initialising the probability as we have to add log of probability of each word
    for j in range(len(x)):
        if(x[j]!=0):
            output=np.log((count[current_class][j])+1)-np.log((count[current_class]["total"])+num_features)
            prob+=output
    return prob

In [37]:
def predictionSinglePoint(count,x):
    #to find the pedinction of the given document
    classes=count.keys()
    best_p=-99999
    best_c=""
    first_run=True
    for current_class in classes:
        #checking for each label and returning the one with highest probability
        if current_class=="total_data":     
            continue
        p_current_class=probability(count,x,current_class)
        if(first_run or p_current_class>best_p):
            best_p=p_current_class
            best_c=current_class
        first_run=False
    return best_c

In [38]:
def predict(count,x_test):
    #function to predict the label of all the data
    y_pred=[]
    for x in x_test:
        x_class=predictionSinglePoint(count,x)
        y_pred.append(x_class)
    return y_pred

In [39]:
#fitting the data and save the counts in count
count=fit(x_train,y_train)

In [40]:
y_pred_own=predict(count,x_test)

In [41]:
y_pred_own

['talk.politics.mideast',
 'rec.sport.hockey',
 'rec.sport.baseball\\',
 'alt.atheism',
 'comp.os.ms-windows.misc',
 'soc.religion.christian',
 'sci.med',
 'comp.graphics',
 'soc.religion.christian',
 'soc.religion.christian',
 'rec.sport.baseball\\',
 'rec.sport.baseball\\',
 'soc.religion.christian',
 'rec.sport.hockey',
 'rec.sport.baseball\\',
 'talk.religion.misc',
 'talk.politics.misc\\',
 'rec.sport.baseball\\',
 'sci.crypt',
 'sci.electronics',
 'talk.politics.mideast',
 'comp.sys.mac.hardware',
 'alt.atheism',
 'sci.electronics',
 'comp.windows.x',
 'rec.autos\\',
 'sci.electronics',
 'rec.autos\\',
 'talk.religion.misc',
 'sci.electronics',
 'rec.motorcycles\\',
 'rec.sport.baseball\\',
 'sci.med',
 'sci.electronics',
 'rec.motorcycles\\',
 'sci.med',
 'rec.autos\\',
 'sci.med',
 'comp.windows.x',
 'sci.med',
 'sci.electronics',
 'rec.sport.baseball\\',
 'misc.forsale',
 'soc.religion.christian',
 'comp.sys.ibm.pc.hardware',
 'rec.sport.baseball\\',
 'soc.religion.christian',

In [42]:
from sklearn.metrics import classification_report,confusion_matrix

In [43]:
print(classification_report(y_test,y_pred_own))
print(confusion_matrix(y_test,y_pred_own))

                          precision    recall  f1-score   support

             alt.atheism       0.50      0.55      0.52       249
           comp.graphics       0.56      0.45      0.50       224
  comp.os.ms-windows.mis       0.25      0.32      0.28       150
 comp.os.ms-windows.misc       0.22      0.26      0.24       111
comp.sys.ibm.pc.hardware       0.41      0.27      0.33       245
   comp.sys.mac.hardware       0.47      0.40      0.43       264
          comp.windows.x       0.59      0.42      0.49       246
            misc.forsale       0.53      0.75      0.62       230
              rec.autos\       0.52      0.53      0.53       255
         rec.motorcycles       0.00      0.00      0.00         0
        rec.motorcycles\       0.33      0.51      0.40       253
      rec.sport.baseball       0.00      0.00      0.00         0
     rec.sport.baseball\       0.46      0.52      0.49       252
        rec.sport.hockey       0.67      0.55      0.60       251
         

G:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [44]:
print(accuracy_score(y_test,y_pred_own))

0.497
